#Expyriment 0.11.dev5 (Python 3.12.0), .xpe-file, coding: UTF-8
#date: Wed Oct 16 2024 15:59:18
#sha1: 740521
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Linux', node='is154920', release='6.8.0-45-lowlatency', version='#45.1~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep  6 15:26:10 UTC', machine='x86_64')
Time,Type,Event,Value,Detail,Detail2
1010,design,log,
#design: #exp: Experiment
#design: block_cnt,block_id,trial_cnt,trial_id
1010,design,logged,
1010,Experiment,started
1010,stderr,received,'Traceback (most recent call last):'
1010,stderr,received,'  File "/home/cp983411/00_git/ppe/experiments/kinematogram/kine.py", line 30, in <module>'
1010,stderr,received,'    k.present_and_wait_keyboard()'
1010,stderr,received,'  File "/home/cp983411/.pyenv/versions/expyriment-py3.12-0.11.0.dev3/.expyriment/extras/expyriment_stimuli_extras/randomdotkinematogram/_randomdotkinematogram.py", line 251, in present_and_wait_keyboard'
1011,stderr,received,'    from .. import _internals'
1011,stderr,received,"ImportError: cannot import name '_internals' from 'expyriment_stimuli_extras' (/home/cp983411/.pyenv/versions/expyriment-py3.12-0.11.0.dev3/.expyriment/extras/expyriment_stimuli_extras/__init__.py)"
